export const WORDS_DOUBLE = [
  'applejuice',
  'freshbread',
  'whitehouse',
  'heartthrob',
  'fancypants',
  'stockissue',
  'housemouse',
  'firsttimer',
  'extrapoint',
  'smartphone',
  'lightsaber',
  'toothfairy',
  'alarmclock',
  'dirtymoney',
]

// 'earthfirst',
// 'panemgames',
// 'grassfield',
// 'jellybread',
// 'saltysnack',
// 'sugarbombs',
// 'shelfbooks',
// 'superduper',
